[package]
name = "web-runnables"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread", "macros"] }
regex = "1.11.1"
serde_yaml = "0.9.34"
notify = "8.0.0"
